name: level_up_shared
description: "Models and views shared between level_up and level_up_coach"
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  go_router: ^15.0.0
  google_sign_in: ^6.3.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/apple_white.svg
    - lib/assets/images/google_icon.png
